overtime/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'overtime.views.index', name='overtime'),
    url(r'^filter_all/$', 'overtime.views.filter_all', name='filter_all_overtime'),
    url(r'^filter_new/$', 'overtime.views.filter_new', name='filter_new_overtime'),
    url(r'^filter_applying/$', 'overtime.views.filter_applying', name='filter_applying_overtime'),
    url(r'^filter_approved/$', 'overtime.views.filter_approved', name='filter_approved_overtime'),
    url(r'^(?P<id>\d+)/$', 'overtime.views.show', name='show_overtime'),
    url(r'^new/$', 'overtime.views.new', name='new_overtime'),
    url(r'^overview/$', 'overtime.views.overview', name='overview_overtime'),
    url(r'^excel/$', 'overtime.views.excel', name='excel_overtime'),
    url(r'^(?P<id>\d+)/edit/$', 'overtime.views.edit', name='edit_overtime'),
    url(r'^(?P<id>\d+)/delete/$', 'overtime.views.delete', name='delete_overtime'),
    url(r'^(?P<id>\d+)/approve/$', 'overtime.views.approve', name='approve_overtime'),
    url(r'^(?P<id>\d+)/reject/$', 'overtime.views.reject', name='reject_overtime'),
    url(r'^(?P<id>\d+)/apply/$', 'overtime.views.apply', name='apply_overtime'),
    url(r'^(?P<id>\d+)/revoke/$', 'overtime.views.revoke', name='revoke_overtime'),
    url(r'^filter_date/$', 'overtime.views.filter_date', name='filter_date_overtime'),
)

urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic.simple import direct_to_template

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', direct_to_template, {'template':'index.html'}),
    # url(r'^hrms/', include('hrms.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^overtime/', include('overtime.urls')),
    url(r'^about/$', direct_to_template, {'template':'about.html'}),
    url(r'^accounts/login/$', login, {'template_name':'login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page':'/'}, name='logout'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

overtime/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
import datetime

class UserProfileManager(models.Manager):
    def userprofile_in_employee_and_PM(self):
        profiles = []
        group = Group.objects.get(name='员工')
        for user in group.user_set.all():
            profiles.append(user.userprofile)
        group = Group.objects.get(name='项目经理')
        for user in group.user_set.all():
            profiles.append(user.userprofile)
        return UserProfile.objects.filter(id__in=[o.id for o in profiles])

class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    superior = models.ForeignKey(User, null=True, related_name='subordinates')
    chinese_name = models.CharField(max_length=100)
    english_name = models.CharField(max_length=100, null=True)
    objects = UserProfileManager()
    
    def __unicode__(self):
        return self.chinese_name
    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        
post_save.connect(create_user_profile, sender=User)

class ApplicationState(models.Model):
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name
                
class Application(models.Model):
    subject = models.CharField(max_length=100, verbose_name='主题')
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    application_date = models.DateTimeField(auto_now_add=True)
    participants = models.ManyToManyField(User, null=True, related_name='joined_applications', verbose_name='参加人员')
    state = models.ForeignKey(ApplicationState, editable=False, null=True)
    applicant = models.ForeignKey(User, related_name='applied_applications', editable=False)
    content = models.TextField(verbose_name='备注')
    modified_by = models.ForeignKey(User, editable=False)
    modified_on = models.DateTimeField(auto_now=True, editable=False)

    @property
    def participants_string(self):
        return ', '.join([person.userprofile.chinese_name for person in self.participants.all()])
        
    @property
    def total_time(self):
        begin = self.start_time
        print begin
        if self.start_time.hour < 19:
            begin = datetime.datetime(self.start_time.year, self.start_time.month, self.start_time.day, 19, 0, 0)
        total = int((self.end_time-begin).total_seconds()/3600)
        if total < 0:
            total = 0
        return total
        
    def applicationflow_by_user(self, user):
        try:
            return self.applicationflow_set.get(applicant=user)
        except:
            return None
            
    def create(self, user, new_app):
        self.state = ApplicationState.objects.get(code='ReadyForDirectorApprove')
        self.applicant = user
        self.modified_by = user
        self.save()
        participants = []
        for userprofile in new_app['participants']:
            participants.append(userprofile.user)
        self.participants = participants
        
        # application flow for current user
        current_flow = ApplicationFlow()
        current_flow.application = self
        current_flow.applicant = self.applicant
        current_flow.set_applicant_state()
        current_flow.save()

        # application flow for participants
        for participant in self.participants.all():
            if participant != self.applicant:
                app_flow = ApplicationFlow()
                app_flow.application = self
                app_flow.applicant = participant
                app_flow.set_viewer_state()
                app_flow.save()

        # application flow for superior
        next_flow = ApplicationFlow()
        next_flow.application = self
        next_flow.applicant = user.userprofile.superior
        next_flow.parent = current_flow
        next_flow.set_reviewer_state()
        next_flow.save()
        
        # application history
        self.write_history(user)
        
        return user.userprofile.superior
        
    def update(self, new_app):
        """new_app is a dictionary"""
        # delete application flow for old participants
        for participant in self.participants.all():
            if participant != self.applicant:
                app_flow = self.applicationflow_by_user(participant)
                if app_flow is not None:
                    app_flow.delete()
          
        participants = []
        for userprofile in new_app['participants']:
            participants.append(userprofile.user)
        self.participants = participants
        
        # create application flow for new participants
        for participant in self.participants.all():
            if participant != self.applicant:
                app_flow = ApplicationFlow()
                app_flow.application = self
                app_flow.applicant = participant
                app_flow.set_viewer_state()
                app_flow.save() 
        
        self.save()
        
    def revoke(self, user):
        self.state = ApplicationState.objects.get(code='Revoke')
        self.save()
        
        flow = self.applicationflow_by_user(user)
        flow.set_revoke_state()
        flow.save()

        flow = self.applicationflow_by_user(user.userprofile.superior)
        flow.delete()
        
        # application history
        self.write_history(user)
        
        return user.userprofile.superior
        
    def apply(self, user):
        self.state = ApplicationState.objects.get(code='ReadyForDirectorApprove')
        self.save()
        
        current_flow = self.applicationflow_by_user(user)
        current_flow.set_applicant_state()
        current_flow.save()

        next_flow = ApplicationFlow()
        next_flow.application = self
        next_flow.applicant = user.userprofile.superior
        next_flow.parent = current_flow
        next_flow.set_reviewer_state()
        next_flow.save()
        
        # application history
        self.write_history(user)
        
        return user.userprofile.superior

    def reject(self, user):
        self.state = ApplicationState.objects.get(code='Reject')
        self.save()
        
        flow = self.applicationflow_by_user(user)
        # change parent flow state
        parent_flow = flow.parent
        parent_flow.set_revoke_state()
        parent_flow.save()
        # delete current flow
        flow.delete()
        
        # application history
        self.write_history(user)
        
        return parent_flow.applicant
        
    def approve(self, user):
        self.state = ApplicationState.objects.get(code='Approved')
        self.save()
        
        applicant_flow = self.applicationflow_by_user(self.applicant)
        applicant_flow.set_hidden_state()
        applicant_flow.save()
        
        current_flow = self.applicationflow_by_user(user)
        if user.userprofile.superior is None:
            current_flow.delete()
        else:
            current_flow.set_hidden_state()
            current_flow.save()

            next_flow = ApplicationFlow()
            next_flow.application = self
            next_flow.applicant = user.userprofile.superior
            next_flow.parent = current_flow
            next_flow.set_reviewer_state()
            next_flow.save()
            
        # application history
        self.write_history(user)
            
    def write_history(self, user):
        history = ApplicationHistory()
        history.application = self
        history.modified_by = user
        history.state = self.state
        history.save()
        self.modified_by = user
        self.save()
    
    def __unicode__(self):
        return self.subject
        
class ApplicationFlow(models.Model):
    application = models.ForeignKey(Application)
    applicant = models.ForeignKey(User)
    parent = models.ForeignKey('self', null=True)
    #permissions
    can_read = models.BooleanField()    # 列表
    can_update = models.BooleanField()  # 修改
    can_delete = models.BooleanField()  # 删除
    can_apply = models.BooleanField()   # 提交
    can_revoke = models.BooleanField()  # 撤销
    can_reject = models.BooleanField()  # 拒绝
    can_approve = models.BooleanField() # 通过
    
    # 申请人    
    def set_applicant_state(self):
        self.reset_state()
        self.can_read = True
        self.can_revoke = True
        
    # 申请人撤销
    def set_revoke_state(self):
        self.reset_state()
        self.can_update = True
        self.can_delete = True
        self.can_apply = True
    
    # 参加人
    def set_viewer_state(self):
        self.reset_state()
        self.can_read = True
     
    # 批准过的人
    def set_hidden_state(self):
        self.reset_state()

    # 审核人
    def set_reviewer_state(self):
        self.reset_state()
        self.can_read = True
        self.can_reject = True
        self.can_approve = True
        
    def reset_state(self):
        self.can_read = False
        self.can_update = False
        self.can_delete = False
        self.can_apply = False
        self.can_revoke = False
        self.can_reject = False
        self.can_approve = False
        
    def __unicode__(self):
        return str(self.id)
        
class ApplicationHistory(models.Model):
    application = models.ForeignKey(Application)
    modified_by = models.ForeignKey(User)
    modified_on = models.DateTimeField(auto_now_add=True)
    state = models.ForeignKey(ApplicationState)

templates/overtime/email.html
<p><a href="{{ app_url }}">{{ app.subject }}</a></p>
<p>{{ app.state }}</p>

templates/overtime/form.html
{% extends "base.html" %}

{% block title %}{% if form.instance.id %}修改加班{% else %}新增加班{% endif %}{% endblock %}

{% block content %} 

  <ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <li><a href="/overtime">加班系统</a> <span class="divider">/</span></li>
    <li class="active">{% if form.instance.id %}修改加班{% else %}新增加班{% endif %}</li>
  </ul>

  <div class="page-header"><h1>{% if form.instance.id %}修改加班{% else %}新增加班{% endif %}</h1></div>
  
  <form method="post" class="form-horizontal">
      {% csrf_token %}
      {% for field in form %}
      <div class="control-group">
        <label for="id_subject" class="control-label">{{ field.label }}</label>
        <div class="controls">
          {{ field }}
          {% if field.errors %}<div class="alert alert-error">{{ field.errors }}</div>{% endif %}
        </div>
      </div>
      {% endfor %}
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn">提交</button>
          <input type="hidden" name="next" value="{{ next }}" />
        </div>
      </div>
  </form>

  <p>
    <a class="btn" href="{% url overtime %}">返回</a>
  </p>
  
{% endblock %}

{% block js %} 
 
  <script type="text/javascript" charset="utf-8">
    $('#id_start_time').datetimepicker({dateFormat: "yy-mm-dd"});
    $('#id_end_time').datetimepicker({dateFormat: "yy-mm-dd"});
  </script>
        
{% endblock %}

templates/overtime/index.html
{% extends "base.html" %}

{% block title %}加班系统{% endblock %}

{% block content %} 

  <ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <li class="active">加班系统</li>
  </ul>

  <div class="page-header"><h1>加班列表</h1></div>
  
  <p>
    {% if "overtime.add_application" in request.user.get_group_permissions %}<a class="btn" href="{% url new_overtime %}">新增加班申请</a>{% endif %}
    <a class="btn" href="{% url overview_overtime %}">加班统计</a>
  </p>
      
  {% if "overtime.filter_application" in request.user.get_group_permissions %}
  <p>
    <span id="date-filter" class="pull-right" onclick="showDatePicker();">{{ date_filter }}</span>
    <ul class="nav nav-tabs">
      <li class="{% ifequal filter 'all' %}active{% endifequal %}"><a href="{% url filter_all_overtime %}">全部</a></li>
      <li class="{% ifequal filter 'new' %}active{% endifequal %}"><a href="{% url filter_new_overtime %}">未提交</a></li>
      <li class="{% ifequal filter 'applying' %}active{% endifequal %}"><a href="{% url filter_applying_overtime %}">申请中</a></li>
      <li class="{% ifequal filter 'approved' %}active{% endifequal %}"><a href="{% url filter_approved_overtime %}">通过</a></li>
    </ul>
  </p>
  {% endif %}
  
  

  {% if is_hr %}
    {% for app in applications %}
    <li>
        <h3><a href="{% url show_overtime app.id %}">{{ app.subject }}</a></h3>
        {{ app.state }}
        <div class="foot">最后由 • <span class="field">{{ app.modified_by.userprofile.chinese_name }}</span> • 于 • <span class="field">{{ app.modified_on|date:"Y年n月j日 H:i" }}</span> • 修改</div>
    </li>
    {% endfor %}
  {% else %}
    {% for flow in application_flows %}
  <div class="row">
    <div class="span12">
      <h4>
        <a href="{% url show_overtime flow.application.id %}">{{ flow.application.subject }}</a>
        <span class="label label-{{ flow.application.state.code }}" id="app_state">{{ flow.application.state }}</span>
      </h4>
      <small>最后由 • <strong>{{ flow.application.modified_by.userprofile.chinese_name }}</strong> • 于 • <strong>{{ flow.application.modified_on|date:"Y年n月j日 H:i" }}</strong> • 修改</small>
      <div class="pull-right">
        {% if flow.can_update %}<a class="btn btn-small" href="{% url edit_overtime flow.application.id %}">修改</a>{% endif %}
        {% if flow.can_approve %}<a class="btn btn-small" href="{% url approve_overtime flow.application.id %}">通过</a>{% endif %}
        {% if flow.can_reject %}<a class="btn btn-small" href="{% url reject_overtime flow.application.id %}">拒绝</a>{% endif %}
        {% if flow.can_apply %}<a class="btn btn-small" href="{% url apply_overtime flow.application.id %}">提交</a>{% endif %}
        {% if flow.can_revoke %}<a class="btn btn-small" href="{% url revoke_overtime flow.application.id %}">撤销</a>{% endif %}
        {% if flow.can_delete %}<a class="btn btn-small" href="{% url delete_overtime flow.application.id %}" onclick="return confirm('删除以后不能恢复的，确定？')">删除</a>{% endif %}
      </div>
    </div>
  </div>
  <hr>
    {% endfor %}
  {% endif %}

{% endblock %}

templates/overtime/overview.html
{% extends "base.html" %}

{% block title %}加班统计{% endblock %}

{% block content %} 

  <ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <li><a href="/overtime">加班系统</a> <span class="divider">/</span></li>
    <li class="active">加班统计</li>
  </ul>

  <div class="page-header"><h1>加班统计</h1></div>
  
  <span class="pull-right" id="date-filter" onclick="showDatePicker();">{{ date_filter }}</span>
  <a class="btn" href="{% url excel_overtime %}">导出报表</a>

  <div class="row">
    <div class="span5">
      <h2>基本信息</h2>
      <table class="table table-condensed">
        <tbody>
          <tr><th>姓名</th><td>{{ request.user.userprofile.chinese_name }}</td></tr>
          <tr><th>部门</th><td></td></tr>
          <tr><th>入职日期</th><td></td></tr>
          <tr><th>已休年假天数</th><td></td></tr>
          <tr><th>年假剩余天数</th><td></td></tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <h2>加班信息</h2>
      <table class="table table-striped table-condensed">
        <thead><tr><th>#</th><th>标题</th><th>开始时间</th><th>结束时间</th><th>加班时间(小时)</th></tr></thead>
        <tbody>
          {% for flow in application_flows %}
          <tr><td>{{ forloop.counter }}</td><td>{{ flow.application.subject }}</td><td>{{ flow.application.start_time|date:"Y年n月j日 H:i" }}</td><td>{{ flow.application.end_time|date:"Y年n月j日 H:i" }}</td><td>{{ flow.application.total_time }}</td></tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <p>
    <a class="btn" href="{% url overtime %}">返回</a>
  </p>
   
{% endblock %}

templates/overtime/show.html
{% extends "base.html" %}

{% block title %}加班详情{% endblock %}

{% block content %} 

  <ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <li><a href="/overtime">加班系统</a> <span class="divider">/</span></li>
    <li class="active">加班详情</li>
  </ul>

  <div class="page-header"><h1>{{ app.subject }}</h1></div>

  <div class="row">
    <div class="span5">
      <table class="table table-condensed">
        <tr><th>主题:</th><td>{{ app.subject }}</td></tr>
        <tr><th>申请人:</th><td>{{ app.applicant.userprofile.chinese_name }}</td></tr>
        <tr><th>开始时间:</th><td>{{ app.start_time|date:"Y年n月j日 H:i" }}</td></tr>
        <tr><th>结束时间:</th><td>{{ app.end_time|date:"Y年n月j日 H:i" }}</td></tr>
        <tr><th>申请日期:</th><td>{{ app.application_date|date:"Y年n月j日 H:i" }}</td></tr>
        <tr><th>参加人员:</th><td>{{ app.participants_string }}</td></tr>
        <tr><th>备注:</th><td>{{ app.content }}</td></tr>
        <tr><th>状态:</th><td>{{ app.state.name }}</td></tr>
      </table>
    </div>
  </div>

  <h2>修改历史</h2>
  <table class="table table-condensed">
    <thead><tr><th>时间</th><th>修改人</th><th>状态</th></tr></thead>
    <tbody>
    {% for history in app.applicationhistory_set.all %}
    <tr><td>{{ history.modified_on|date:"Y年n月j日 H:i" }}</td><td>{{ history.modified_by.userprofile.chinese_name }}</td><td>{{ history.state }}</td></tr>
    {% endfor %}
    </tbody>
  </table>

  <p>
    <a class="btn" href="{% url overtime %}">返回</a>
  </p>

{% endblock %}